name: Firebase Functions CI/CD

on:
  push:
    branches: [ main, develop ]
    paths: [ 'functions/**' ]
  pull_request:
    branches: [ main, develop ]
    paths: [ 'functions/**' ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: functions/package-lock.json
    
    - name: Install dependencies
      run: |
        cd functions
        npm ci
    
    - name: Run linting
      run: |
        cd functions
        npm run lint
    
    - name: Build functions
      run: |
        cd functions
        npm run build
    
    - name: Type check
      run: |
        cd functions
        npm run type-check

  deploy:
    needs: test-and-build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    environment: production
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: functions/package-lock.json
    
    - name: Install dependencies
      run: |
        cd functions
        npm ci
    
    - name: Build functions
      run: |
        cd functions
        npm run build
    
    - name: Setup Firebase CLI
      run: npm install -g firebase-tools
    
    - name: Deploy to Firebase Functions
      run: |
        # Create temporary service account file
        echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > service-account.json
        
        # Set environment variable for Firebase CLI
        export GOOGLE_APPLICATION_CREDENTIALS=service-account.json
        
        # Deploy only functions with cleanup policy
        firebase deploy --only functions --project '${{ secrets.FIREBASE_PROJECT_ID }}' --force
        
        # Clean up
        rm -f service-account.json
      env:
        FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
